name: CI Pipeline


on:
    pull_request:
        branches: ["main"]

env:
    IMAGE_NAME: rdicidr:0.1.0
    TAG: latest


jobs:
    build_code:
        name: 'Code Build'
        runs-on: ubuntu-latest

        steps:

            # Checkout
            - name: 'Checkout code'
              uses: actions/checkout@v3
            
            # Node Setup  
            - name: 'Setup Node 15'
              uses: actions/setup-node@v3
              with:
                node-version: '15'  

            - name: 'Install dependencies'
               run: npm --prefix codebase/rdicidr-0.1.0 install
              
            - name: 'Linter (ESLint)'
               run: npm --prefix codebase/rdicidr-0.1.0 run lint
               
            - name: 'Formatter (Prettier)'
               run: npm --prefix codebase/rdicidr-0.1.0 run prettier
               
            - name: 'Test (Jest)'
               run: npm --prefix codebase/rdicidr-0.1.0 run test
               
            - name: 'Build'
               run: npm --prefix codebase/rdicidr-0.1.0 run build  
            